# Generated by Django 4.0.1 on 2022-01-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigner',
            field=models.CharField(default='nickdavis', max_length=50),
        ),
        migrations.AddField(
            model_name='assignment',
            name='urgency',
            field=models.CharField(default='standard', max_length=50),
        ),
    ]
