# Generated by Django 4.0.1 on 2022-01-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assignment_flagged_alter_assignment_assigner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='urgency',
            field=models.BooleanField(default=False),
        ),
    ]
